---
name: Template-Sandbox
version: 1.01_01
author:
  - 'Sam Graham <libtemplate-sandbox-perl@illusori.co.uk>'
abstract: Templates safely sandboxed from your application.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.07
  Test::Exception: 0
  Test::More: 0
requires:
  Carp: 0
  Class::Handle: 0
  Clone: 0
  Cwd: 0
  Data::Dumper: 0
  Digest: 0
  Digest::MD5: 0
  IO::File: 0
  Log::Any: 0.03
  Scalar::Util: 0
  Storable: 1.014
recommends:
  Cache::Cache: 1
  Cache::CacheFactory: 1.08
configure_requires:
  Module::Build: 0.34
dynamic_config: 0
provides:
  Template::Sandbox:
    file: lib/Template/Sandbox.pm
    version: 1.01_01
  Template::Sandbox::Library:
    file: lib/Template/Sandbox/Library.pm
    version: 1.01
  Template::Sandbox::NumberFunctions:
    file: lib/Template/Sandbox/NumberFunctions.pm
    version: 1.01
  Template::Sandbox::StringFunctions:
    file: lib/Template/Sandbox/StringFunctions.pm
    version: 1.01
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
